In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("../data/raw/city_of_houston/floodingdrainage2015.csv")

In [8]:
df.head()

   weight        lat        lon
0       1  29.862192 -95.294884
1       1  29.694897 -95.299593
2       1  29.684477 -95.518639
3       1  29.773975 -95.466208
4       1  29.819542 -95.391873

In [9]:
print("Dataset shape:", df.shape)
print("Column names:", df.columns.tolist())

Dataset shape: (14167, 3)
Column names: ['weight', 'lat', 'lon']

In [10]:
print(df.isnull().sum())

weight    0
lat       0
lon       0
dtype: int64

In [11]:
print("Zero latitude values:", (df["lat"] == 0).sum())
print("Zero longitude values:", (df["lon"] == 0).sum())
print("Latitude range:", df["lat"].min(), "to", df["lat"].max())
print("Longitude range:", df["lon"].min(), "to", df["lon"].max())

Zero latitude values: 0
Zero longitude values: 0
Latitude range: 29.54281652 to 30.08434706
Longitude range: -95.77240952 to -95.0943833

In [12]:
print("Unique weight values:", df["weight"].nunique())
print("\nWeight distribution:")
print(df["weight"].value_counts().sort_index())

Unique weight values: 1

Weight distribution:
weight
1    14167
Name: count, dtype: int64

In [13]:
duplicate_count = df.duplicated(subset=["lat", "lon"]).sum()
print("Duplicate coordinate rows:", duplicate_count)
print("Unique coordinate locations:", len(df) - duplicate_count)

Duplicate coordinate rows: 3158
Unique coordinate locations: 11009

In [14]:
location_counts = df.groupby(["lat", "lon"]).size()
print("Most frequently repeated locations:")
print(location_counts.sort_values(ascending=False).head(10))

Most frequently repeated locations:
lat        lon
29.651376  -95.479199    19
29.784048  -95.193927    19
29.677557  -95.509598    16
29.679244  -95.505591    16
29.792249  -95.524460    16
29.751726  -95.382602    14
29.706230  -95.403015    13
29.779228  -95.386652    13
29.802243  -95.522672    11
29.615419  -95.339007    11
dtype: int64

In [15]:
df_locations = (
    df.groupby(["lat", "lon"])
      .size()
      .reset_index(name="report_count")
)

df_locations.head()

         lat        lon  report_count
0  29.542817 -95.145052             1
1  29.545944 -95.138742             3
2  29.546423 -95.139367             1
3  29.546556 -95.148015             1
4  29.550232 -95.126686             1

In [16]:
print("Original number of rows:", len(df))
print("Number of unique locations:", len(df_locations))
print("Total records after aggregation:", df_locations["report_count"].sum())

Original number of rows: 14167
Number of unique locations: 11009
Total records after aggregation: 14167

In [17]:
for year in [2016, 2017, 2019]:
    path = f"../data/raw/city_of_houston/floodingdrainage{year}.csv"
    yearly_df = pd.read_csv(path)

    print(f"Year: {year}")
    print("Shape:", yearly_df.shape)
    print("Columns:", yearly_df.columns.tolist())
    print()

Year: 2016
Shape: (14143, 3)
Columns: ['weight', 'lat', 'lon']

Year: 2017
Shape: (14559, 3)
Columns: ['weight', 'lat', 'lon']

Year: 2019
Shape: (12426, 3)
Columns: ['weight', 'lat', 'lon']

In [18]:
for year in [2016, 2017, 2019]:
    path = f"../data/raw/city_of_houston/floodingdrainage{year}.csv"
    yearly_df = pd.read_csv(path)

    print(f"Year: {year}")
    print(yearly_df.isnull().sum())
    print()

Year: 2016
weight    0
lat       0
lon       0
dtype: int64

Year: 2017
weight    0
lat       0
lon       0
dtype: int64

Year: 2019
weight    0
lat       0
lon       0
dtype: int64

In [19]:
for year in [2016, 2017, 2019]:
    path = f"../data/raw/city_of_houston/floodingdrainage{year}.csv"
    yearly_df = pd.read_csv(path)

    print(f"Year: {year}")
    print("Zero latitude values:", (yearly_df["lat"] == 0).sum())
    print("Zero longitude values:", (yearly_df["lon"] == 0).sum())
    print("Latitude range:", yearly_df["lat"].min(), "to", yearly_df["lat"].max())
    print("Longitude range:", yearly_df["lon"].min(), "to", yearly_df["lon"].max())
    print()

Year: 2016
Zero latitude values: 0
Zero longitude values: 0
Latitude range: 29.44673985 to 30.09049013
Longitude range: -95.76152736 to -95.05463929

Year: 2017
Zero latitude values: 0
Zero longitude values: 0
Latitude range: 29.53088025 to 30.21149134
Longitude range: -95.78871185 to -95.09426872

Year: 2019
Zero latitude values: 0
Zero longitude values: 0
Latitude range: 29.54485703 to 30.17309556
Longitude range: -95.74382386 to -95.00632176

In [20]:
for year in [2016, 2017, 2019]:
    path = f"../data/raw/city_of_houston/floodingdrainage{year}.csv"
    yearly_df = pd.read_csv(path)

    duplicate_count = yearly_df.duplicated(
        subset=["lat", "lon"]
    ).sum()

    unique_locations = len(yearly_df) - duplicate_count

    print(f"Year: {year}")
    print("Total records:", len(yearly_df))
    print("Duplicate coordinate rows:", duplicate_count)
    print("Unique locations:", unique_locations)
    print()

Year: 2016
Total records: 14143
Duplicate coordinate rows: 2997
Unique locations: 11146

Year: 2017
Total records: 14559
Duplicate coordinate rows: 2708
Unique locations: 11851

Year: 2019
Total records: 12426
Duplicate coordinate rows: 2663
Unique locations: 9763

In [21]:
yearly_locations = {}

for year in [2015, 2016, 2017, 2019]:
    path = f"../data/raw/city_of_houston/floodingdrainage{year}.csv"
    yearly_df = pd.read_csv(path)

    aggregated_df = (
        yearly_df.groupby(["lat", "lon"])
        .size()
        .reset_index(name="report_count")
    )

    aggregated_df["year"] = year
    yearly_locations[year] = aggregated_df

    print(f"{year}: {len(aggregated_df)} unique locations")

2015: 11009 unique locations
2016: 11146 unique locations
2017: 11851 unique locations
2019: 9763 unique locations

In [22]:
for year in [2015, 2016, 2017, 2019]:
    df_year = yearly_locations[year]

    print(f"Year: {year}")
    print("Unique locations:", len(df_year))
    print("Total records represented:", df_year["report_count"].sum())
    print()

Year: 2015
Unique locations: 11009
Total records represented: 14167

Year: 2016
Unique locations: 11146
Total records represented: 14143

Year: 2017
Unique locations: 11851
Total records represented: 14559

Year: 2019
Unique locations: 9763
Total records represented: 12426

In [23]:
from pathlib import Path

data_folder = Path("../data")

for file in data_folder.rglob("*"):
    if file.suffix.lower() in [".shp", ".geojson", ".gpkg"]:
        print(file)

..\data\boundaries\houston_city_limits.geojson

In [24]:
import geopandas as gpd

houston_boundary = gpd.read_file("../data/boundaries/houston_city_limits.geojson")

houston_boundary.head()

,OBJECTID_1,SERVICE_TY,DESCRIPTIO,ENTITY_NAM,EFF_DATE,LEGAL_DOC,COMMENTS,COUNCIL_AP,ANNEXATION,POLICE_SER,...,HEALTH_INS,FW_ENTIREL,FW_SALES_B,STREET_LIG,BUILDING_C,OTHER,Ord_Link,Shape.STArea(),Shape.STLength(),geometry
0,227776,LIMITED,174,White Oak Bend MUD,1.174435e+12,2007-0383,NaN,1.174435e+12,2007-0383,No,...,No,Yes,Yes,No,No,no,NaN,1.173060e+06,6839.805838,"POLYGON ((-95.58378 29.9254, -95.58378 29.9256..."
1,227777,LIMITED,145,Mills Road MUD,1.150848e+12,2006-0701,ROW,1.150848e+12,2006-0701,No,...,No,Yes,Yes,No,No,NaN,NaN,5.877610e+05,12680.287035,"POLYGON ((-95.56509 29.95903, -95.56635 29.959..."
2,227778,LIMITED,69,Cypress Hill MUD 1,1.071014e+12,2003-1222,NaN,1.071014e+12,2003-1222,No,...,No,Yes,Yes,No,No,NaN,NaN,1.931357e+05,2348.931168,"POLYGON ((-95.69734 29.99661, -95.69732 29.996..."
3,227779,LIMITED,169,Northwest Park MUD (1st Amendment),1.174435e+12,2007-0385,ROW,1.174435e+12,2007-0385,No,...,No,No,Yes,No,No,no,NaN,1.568833e+05,3331.739520,"POLYGON ((-95.49239 29.92803, -95.49239 29.928..."
4,227780,LIMITED,91,Reid Rd. MUD 1,1.087344e+12,2004-0602,ROW,1.087344e+12,2004-0602,No,...,No,No,Yes,No,No,NaN,NaN,1.027381e+05,2948.803844,"POLYGON ((-95.57844 29.93348, -95.57797 29.933..."

In [25]:
print("Coordinate Reference System:", houston_boundary.crs)

print("\nGeometry types:")
print(houston_boundary.geometry.geom_type.value_counts())

print("\nService area types:")
print(houston_boundary["SERVICE_TY"].value_counts(dropna=False))

Coordinate Reference System: EPSG:4326

Geometry types:
Polygon         736
MultiPolygon     15
Name: count, dtype: int64

Service area types:
SERVICE_TY
LIMITED    749
FULL         2
Name: count, dtype: int64

In [26]:
houston_city_geometry = houston_boundary.geometry.union_all()

print("Combined geometry type:", houston_city_geometry.geom_type)
print("Is geometry valid:", houston_city_geometry.is_valid)
print("Is geometry empty:", houston_city_geometry.is_empty)

Combined geometry type: MultiPolygon
Is geometry valid: True
Is geometry empty: False

In [27]:
flood_points_2015 = gpd.GeoDataFrame(
    yearly_locations[2015].copy(),
    geometry=gpd.points_from_xy(
        yearly_locations[2015]["lon"],
        yearly_locations[2015]["lat"]
    ),
    crs="EPSG:4326"
)

flood_points_2015.head()

         lat        lon  report_count  year                    geometry
0  29.542817 -95.145052             1  2015  POINT (-95.14505 29.54282)
1  29.545944 -95.138742             3  2015  POINT (-95.13874 29.54594)
2  29.546423 -95.139367             1  2015  POINT (-95.13937 29.54642)
3  29.546556 -95.148015             1  2015  POINT (-95.14801 29.54656)
4  29.550232 -95.126686             1  2015  POINT (-95.12669 29.55023)

In [28]:
inside_houston = flood_points_2015.geometry.intersects(houston_city_geometry)

print("Locations inside Houston:", inside_houston.sum())
print("Locations outside Houston:", (~inside_houston).sum())
print("Total locations:", len(flood_points_2015))

Locations inside Houston: 10958
Locations outside Houston: 51
Total locations: 11009

In [29]:
flood_points_2015["inside_houston"] = inside_houston

print(flood_points_2015["inside_houston"].value_counts())

inside_houston
True     10958
False       51
Name: count, dtype: int64

In [30]:
outside_records = flood_points_2015.loc[
    ~flood_points_2015["inside_houston"],
    "report_count"
].sum()

inside_records = flood_points_2015.loc[
    flood_points_2015["inside_houston"],
    "report_count"
].sum()

print("Original records inside Houston:", inside_records)
print("Original records outside Houston:", outside_records)
print("Total original records:", inside_records + outside_records)

Original records inside Houston: 14113
Original records outside Houston: 54
Total original records: 14167

In [31]:
yearly_flood_points = {2015: flood_points_2015}

for year in [2016, 2017, 2019]:
    df_year = yearly_locations[year]

    flood_points = gpd.GeoDataFrame(
        df_year.copy(),
        geometry=gpd.points_from_xy(
            df_year["lon"],
            df_year["lat"]
        ),
        crs="EPSG:4326"
    )

    flood_points["inside_houston"] = flood_points.geometry.intersects(
        houston_city_geometry
    )

    yearly_flood_points[year] = flood_points

    print(f"Year: {year}")
    print("Inside locations:", flood_points["inside_houston"].sum())
    print("Outside locations:", (~flood_points["inside_houston"]).sum())
    print()

Year: 2016
Inside locations: 11044
Outside locations: 102

Year: 2017
Inside locations: 11765
Outside locations: 86

Year: 2019
Inside locations: 9683
Outside locations: 80

In [32]:
for year in [2015, 2016, 2017, 2019]:
    flood_points = yearly_flood_points[year]

    inside_records = flood_points.loc[
        flood_points["inside_houston"],
        "report_count"
    ].sum()

    outside_records = flood_points.loc[
        ~flood_points["inside_houston"],
        "report_count"
    ].sum()

    print(f"Year: {year}")
    print("Original records inside Houston:", inside_records)
    print("Original records outside Houston:", outside_records)
    print("Total original records:", inside_records + outside_records)
    print()

Year: 2015
Original records inside Houston: 14113
Original records outside Houston: 54
Total original records: 14167

Year: 2016
Original records inside Houston: 14034
Original records outside Houston: 109
Total original records: 14143

Year: 2017
Original records inside Houston: 14466
Original records outside Houston: 93
Total original records: 14559

Year: 2019
Original records inside Houston: 12342
Original records outside Houston: 84
Total original records: 12426

In [33]:
cleaned_flood_points = {}

for year in [2015, 2016, 2017, 2019]:
    flood_points = yearly_flood_points[year]

    cleaned_df = flood_points[
        flood_points["inside_houston"]
    ].copy()

    cleaned_flood_points[year] = cleaned_df

    print(f"Year: {year}")
    print("Remaining locations:", len(cleaned_df))
    print("Original records represented:", cleaned_df["report_count"].sum())
    print()

Year: 2015
Remaining locations: 10958
Original records represented: 14113

Year: 2016
Remaining locations: 11044
Original records represented: 14034

Year: 2017
Remaining locations: 11765
Original records represented: 14466

Year: 2019
Remaining locations: 9683
Original records represented: 12342

In [34]:
flood_points_2015_meters = cleaned_flood_points[2015].to_crs("EPSG:32615")

print("Original CRS:", cleaned_flood_points[2015].crs)
print("Projected CRS:", flood_points_2015_meters.crs)

flood_points_2015_meters.head()

Original CRS: EPSG:4326
Projected CRS: EPSG:32615

,lat,lon,report_count,year,geometry,inside_houston
0,29.542817,-95.145052,1,2015,POINT (292147.871 3270046.499),True
1,29.545944,-95.138742,3,2015,POINT (292765.819 3270381.912),True
2,29.546423,-95.139367,1,2015,POINT (292706.184 3270436.026),True
3,29.546556,-95.148015,1,2015,POINT (291868.378 3270466.277),True
4,29.550232,-95.126686,1,2015,POINT (293942.968 3270835.677),True

In [35]:
spatial_index = flood_points_2015_meters.sindex

nearby_pairs = spatial_index.query(
    flood_points_2015_meters.geometry,
    predicate="dwithin",
    distance=50
)

print("Nearby pairs found:", nearby_pairs.shape[1])
print("First five pairs:")
print(nearby_pairs[:, :5])

Nearby pairs found: 18598
First five pairs:
[[0 1 2 3 4]
 [0 1 2 3 4]]

In [36]:
first_indices = nearby_pairs[0]
second_indices = nearby_pairs[1]

unique_pair_mask = first_indices < second_indices

unique_nearby_pairs = nearby_pairs[:, unique_pair_mask]

print("Total spatial matches:", nearby_pairs.shape[1])
print("Distinct nearby-location pairs:", unique_nearby_pairs.shape[1])
print("First five distinct pairs:")
print(unique_nearby_pairs[:, :5])

Total spatial matches: 18598
Distinct nearby-location pairs: 3820
First five distinct pairs:
[[ 6 20 24 42 45]
 [ 7 22 26 43 47]]

In [37]:
first_points = flood_points_2015_meters.geometry.iloc[
    unique_nearby_pairs[0]
].reset_index(drop=True)

second_points = flood_points_2015_meters.geometry.iloc[
    unique_nearby_pairs[1]
].reset_index(drop=True)

pair_distances = first_points.distance(second_points)

print("Minimum distance:", pair_distances.min())
print("Maximum distance:", pair_distances.max())
print("Average distance:", pair_distances.mean())
print("Median distance:", pair_distances.median())

Minimum distance: 0.0009644551092902507
Maximum distance: 49.99889682407852
Average distance: 33.593604307059806
Median distance: 35.89961264763158

In [38]:
import numpy as np

locations_with_neighbors = np.unique(unique_nearby_pairs)

print("Total 2015 locations:", len(flood_points_2015_meters))
print("Locations with a neighbor within 50m:", len(locations_with_neighbors))
print(
    "Locations without a neighbor within 50m:",
    len(flood_points_2015_meters) - len(locations_with_neighbors)
)

Total 2015 locations: 10958
Locations with a neighbor within 50m: 3845
Locations without a neighbor within 50m: 7113

In [39]:
for year in [2016, 2017, 2019]:
    flood_points_meters = cleaned_flood_points[year].to_crs("EPSG:32615")

    nearby_pairs_year = flood_points_meters.sindex.query(
        flood_points_meters.geometry,
        predicate="dwithin",
        distance=50
    )

    unique_pairs_year = nearby_pairs_year[
        :,
        nearby_pairs_year[0] < nearby_pairs_year[1]
    ]

    locations_with_neighbors_year = np.unique(unique_pairs_year)

    print(f"Year: {year}")
    print("Total locations:", len(flood_points_meters))
    print("Distinct nearby pairs:", unique_pairs_year.shape[1])
    print("Locations with nearby neighbors:", len(locations_with_neighbors_year))
    print()

Year: 2016
Total locations: 11044
Distinct nearby pairs: 3042
Locations with nearby neighbors: 3641

Year: 2017
Total locations: 11765
Distinct nearby pairs: 3875
Locations with nearby neighbors: 4092

Year: 2019
Total locations: 9683
Distinct nearby pairs: 2476
Locations with nearby neighbors: 2893

In [40]:
print("Columns:")
print(cleaned_flood_points[2015].columns.tolist())

print("\nData types:")
print(cleaned_flood_points[2015].dtypes)

print("\nFirst five rows:")
display(cleaned_flood_points[2015].head())

Columns:
['lat', 'lon', 'report_count', 'year', 'geometry', 'inside_houston']

Data types:
lat                float64
lon                float64
report_count         int64
year                 int64
geometry          geometry
inside_houston        bool
dtype: object

First five rows:

,lat,lon,report_count,year,geometry,inside_houston
0,29.542817,-95.145052,1,2015,POINT (-95.14505 29.54282),True
1,29.545944,-95.138742,3,2015,POINT (-95.13874 29.54594),True
2,29.546423,-95.139367,1,2015,POINT (-95.13937 29.54642),True
3,29.546556,-95.148015,1,2015,POINT (-95.14801 29.54656),True
4,29.550232,-95.126686,1,2015,POINT (-95.12669 29.55023),True

In [41]:
export_columns = ["lat", "lon", "report_count", "year"]

export_datasets = {}

for year in [2015, 2016, 2017, 2019]:
    export_df = cleaned_flood_points[year][export_columns].copy()

    export_datasets[year] = export_df

    print(f"Year: {year}")
    print("Rows:", len(export_df))
    print("Columns:", export_df.columns.tolist())
    print()

Year: 2015
Rows: 10958
Columns: ['lat', 'lon', 'report_count', 'year']

Year: 2016
Rows: 11044
Columns: ['lat', 'lon', 'report_count', 'year']

Year: 2017
Rows: 11765
Columns: ['lat', 'lon', 'report_count', 'year']

Year: 2019
Rows: 9683
Columns: ['lat', 'lon', 'report_count', 'year']

In [42]:
from pathlib import Path

output_directory = Path("../data/processed")
output_directory.mkdir(parents=True, exist_ok=True)

for year in [2015, 2016, 2017, 2019]:
    output_path = output_directory / f"houston_311_cleaned_{year}.csv"

    export_datasets[year].to_csv(output_path, index=False)

    print(f"Saved: {output_path}")

Saved: ..\data\processed\houston_311_cleaned_2015.csv
Saved: ..\data\processed\houston_311_cleaned_2016.csv
Saved: ..\data\processed\houston_311_cleaned_2017.csv
Saved: ..\data\processed\houston_311_cleaned_2019.csv

In [43]:
for year in [2015, 2016, 2017, 2019]:
    file_path = output_directory / f"houston_311_cleaned_{year}.csv"

    saved_df = pd.read_csv(file_path)
    original_df = export_datasets[year]

    print(f"Year: {year}")
    print("Saved rows:", len(saved_df))
    print("Columns match:", saved_df.columns.tolist() == original_df.columns.tolist())
    print("Data matches:", saved_df.equals(original_df))
    print("Record count total:", saved_df["report_count"].sum())
    print()

Year: 2015
Saved rows: 10958
Columns match: True
Data matches: False
Record count total: 14113

Year: 2016
Saved rows: 11044
Columns match: True
Data matches: False
Record count total: 14034

Year: 2017
Saved rows: 11765
Columns match: True
Data matches: False
Record count total: 14466

Year: 2019
Saved rows: 9683
Columns match: True
Data matches: False
Record count total: 12342

In [44]:
for year in [2015, 2016, 2017, 2019]:
    file_path = output_directory / f"houston_311_cleaned_{year}.csv"

    saved_df = pd.read_csv(file_path)
    original_df = export_datasets[year]

    print(f"Year: {year}")
    print("Original index:", original_df.index[:5].tolist())
    print("Saved index:", saved_df.index[:5].tolist())

    print(
        "Data matches after resetting index:",
        saved_df.equals(original_df.reset_index(drop=True))
    )
    print()

Year: 2015
Original index: [0, 1, 2, 3, 4]
Saved index: [0, 1, 2, 3, 4]
Data matches after resetting index: True

Year: 2016
Original index: [2, 3, 4, 5, 6]
Saved index: [0, 1, 2, 3, 4]
Data matches after resetting index: True

Year: 2017
Original index: [1, 2, 3, 4, 5]
Saved index: [0, 1, 2, 3, 4]
Data matches after resetting index: True

Year: 2019
Original index: [0, 1, 2, 3, 4]
Saved index: [0, 1, 2, 3, 4]
Data matches after resetting index: True

In [46]:
cleaning_summary = []

for year in [2015, 2016, 2017, 2019]:
    original_df = pd.read_csv(
        f"../data/raw/city_of_houston/floodingdrainage{year}.csv"
    )

    cleaned_df = export_datasets[year]

    cleaning_summary.append({
        "year": year,
        "original_rows": len(original_df),
        "unique_locations_before_filter": len(yearly_locations[year]),
        "locations_after_filter": len(cleaned_df),
        "locations_removed": (
            len(yearly_locations[year]) - len(cleaned_df)
        ),
        "original_rows_represented_after_filter": cleaned_df["report_count"].sum(),
        "original_rows_excluded": (
            len(original_df) - cleaned_df["report_count"].sum()
        )
    })

cleaning_summary_df = pd.DataFrame(cleaning_summary)

display(cleaning_summary_df)

,year,original_rows,unique_locations_before_filter,locations_after_filter,locations_removed,original_rows_represented_after_filter,original_rows_excluded
0,2015,14167,11009,10958,51,14113,54
1,2016,14143,11146,11044,102,14034,109
2,2017,14559,11851,11765,86,14466,93
3,2019,12426,9763,9683,80,12342,84

In [47]:
summary_path = output_directory / "houston_311_cleaning_summary.csv"

cleaning_summary_df.to_csv(summary_path, index=False)

print("Saved cleaning summary:", summary_path)

Saved cleaning summary: ..\data\processed\houston_311_cleaning_summary.csv